### ISSUE TITLE
The webapp does not work

### ISSUE THREAD

**Issue by carlsmith** [jdoubleu/decimal-to-twoscomplement#1]
I typed a number (`255`) into the **Input** field, but nothing happened. The outputs all still say `0`. I tried hitting <kbd>Enter</kbd> and looking for a submit button, but couldn't get anything to happen.

I checked the console, and there are no errors being logged either??

**Comment by jdoubleu** [comment]
Fixed with https://github.com/jdoubleu/decimal-to-twoscomplement/commit/5367ed491f1855d073aa670d5320caf81af8a36d.

I dunno why or how this worked before.

Thanks for the hint!
